/**
 * @file mockPosData.js
 * @description Mock data structures for POS Terminal matching backend API specs (13-menu.md & 14-orders-kitchen.md).
 */

export const RESTAURANT_CATEGORIES = [
  { id: 'cat-all', name: 'All Items', icon: '🍽️' },
  { id: 'cat-starters', name: 'Starters', icon: '🥗' },
  { id: 'cat-mains', name: 'Main Course', icon: '🍲' },
  { id: 'cat-pizzas', name: 'Pizzas & Pasta', icon: '🍕' },
  { id: 'cat-beverages', name: 'Beverages', icon: '🍹' },
  { id: 'cat-desserts', name: 'Desserts', icon: '🍰' },
  { id: 'cat-specials', name: 'Chef Specials', icon: '⭐' },
];

export const TABLES_LIST = [
  { id: 'tbl-01', label: 'Table 01', capacity: 2, section: 'Main Dining', status: 'AVAILABLE' },
  { id: 'tbl-02', label: 'Table 02', capacity: 4, section: 'Main Dining', status: 'OCCUPIED', activeOrder: 'ORD-20260813-0004' },
  { id: 'tbl-03', label: 'Table 03', capacity: 4, section: 'Main Dining', status: 'AVAILABLE' },
  { id: 'tbl-04', label: 'Table 04', capacity: 6, section: 'Main Dining', status: 'RESERVED' },
  { id: 'tbl-05', label: 'Table 05 (Window)', capacity: 2, section: 'Patio', status: 'AVAILABLE' },
  { id: 'tbl-06', label: 'Table 06 (Patio)', capacity: 4, section: 'Patio', status: 'AVAILABLE' },
  { id: 'tbl-VIP1', label: 'VIP Lounge 01', capacity: 8, section: 'VIP Section', status: 'AVAILABLE' },
  { id: 'tbl-VIP2', label: 'VIP Lounge 02', capacity: 10, section: 'VIP Section', status: 'OCCUPIED', activeOrder: 'ORD-20260813-0001' },
];

export const MENU_ITEMS = [
  {
    id: 'mi-101',
    menuNumber: 'APP-01',
    name: 'Pan-Seared Garlic Butter Scallops',
    category: 'Starters',
    price: 450, // INR
    description: 'Fresh sea scallops seared with garlic butter, saffron risotto, herb oil.',
    isVeg: false,
    available: true,
    prepTimeMins: 12,
    station: 'HOT_KITCHEN',
    modifierGroups: [
      {
        id: 'mg-spice',
        name: 'Spice Level',
        required: true,
        options: [
          { id: 'opt-mild', name: 'Mild', priceDelta: 0 },
          { id: 'opt-med', name: 'Medium', priceDelta: 0 },
          { id: 'opt-spicy', name: 'Spicy', priceDelta: 0 },
        ],
      },
      {
        id: 'mg-scallop-addons',
        name: 'Add-ons',
        required: false,
        options: [
          { id: 'opt-truffle', name: 'Extra Truffle Oil Drizzle', priceDelta: 80 },
          { id: 'opt-bread', name: 'Garlic Toast Slice', priceDelta: 40 },
        ],
      },
    ],
  },
  {
    id: 'mi-102',
    menuNumber: 'APP-02',
    name: 'Truffle Burrata Salad',
    category: 'Starters',
    price: 380,
    description: 'Creamy burrata, heirloom tomatoes, pesto oil, aged balsamic glaze.',
    isVeg: true,
    available: true,
    prepTimeMins: 10,
    station: 'COLD_PREP',
    modifierGroups: [],
  },
  {
    id: 'mi-103',
    menuNumber: 'APP-03',
    name: 'Crispy Calamari Rings',
    category: 'Starters',
    price: 390,
    description: 'Tender squid rings served with spicy marinara & lemon garlic aioli.',
    isVeg: false,
    available: true,
    prepTimeMins: 12,
    station: 'HOT_KITCHEN',
    modifierGroups: [],
  },
  {
    id: 'mi-201',
    menuNumber: 'MAIN-01',
    name: 'Grand Horizon Wagyu Burger',
    category: 'Main Course',
    price: 590,
    description: 'Aged wagyu patty, truffle aioli, caramelized onions, brioche bun, side fries.',
    isVeg: false,
    available: true,
    prepTimeMins: 15,
    station: 'HOT_KITCHEN',
    modifierGroups: [
      {
        id: 'mg-doneness',
        name: 'Meat Doneness',
        required: true,
        options: [
          { id: 'opt-med-rare', name: 'Medium Rare', priceDelta: 0 },
          { id: 'opt-med-well', name: 'Medium Well', priceDelta: 0 },
          { id: 'opt-well-done', name: 'Well Done', priceDelta: 0 },
        ],
      },
      {
        id: 'mg-burger-addons',
        name: 'Extras',
        required: false,
        options: [
          { id: 'opt-cheese', name: 'Extra Aged Cheddar', priceDelta: 50 },
          { id: 'opt-bacon', name: 'Crispy Bacon Slice', priceDelta: 70 },
          { id: 'opt-avocado', name: 'Fresh Avocado', priceDelta: 60 },
        ],
      },
    ],
  },
  {
    id: 'mi-202',
    menuNumber: 'MAIN-02',
    name: 'Grilled Norwegian Salmon',
    category: 'Main Course',
    price: 720,
    description: 'Atlantic salmon fillet, lemon dill cream sauce, roasted asparagus.',
    isVeg: false,
    available: true,
    prepTimeMins: 18,
    station: 'HOT_KITCHEN',
    modifierGroups: [],
  },
  {
    id: 'mi-203',
    menuNumber: 'MAIN-03',
    name: 'Wild Mushroom & Truffle Risotto',
    category: 'Main Course',
    price: 490,
    description: 'Arborio rice, porcini mushrooms, parmesan crisps, truffle essence.',
    isVeg: true,
    available: true,
    prepTimeMins: 16,
    station: 'HOT_KITCHEN',
    modifierGroups: [],
  },
  {
    id: 'mi-301',
    menuNumber: 'PIZ-01',
    name: 'Classic Margherita Wood-Fired Pizza',
    category: 'Pizzas & Pasta',
    price: 420,
    description: 'San Marzano tomato, fresh mozzarella, fresh basil, olive oil.',
    isVeg: true,
    available: true,
    prepTimeMins: 14,
    station: 'HOT_KITCHEN',
    modifierGroups: [
      {
        id: 'mg-crust',
        name: 'Crust Option',
        required: true,
        options: [
          { id: 'opt-thin', name: 'Classic Thin Crust', priceDelta: 0 },
          { id: 'opt-cheese-crust', name: 'Cheese Burst Crust', priceDelta: 90 },
        ],
      },
    ],
  },
  {
    id: 'mi-302',
    menuNumber: 'PIZ-02',
    name: 'Spicy Pepperoni & Jalapeño Pizza',
    category: 'Pizzas & Pasta',
    price: 510,
    description: 'Pork pepperoni, hot jalapeños, mozzarella, chili honey drizzle.',
    isVeg: false,
    available: true,
    prepTimeMins: 14,
    station: 'HOT_KITCHEN',
    modifierGroups: [],
  },
  {
    id: 'mi-303',
    menuNumber: 'PAS-01',
    name: 'Fettuccine Creamy Truffle Alfredo',
    category: 'Pizzas & Pasta',
    price: 460,
    description: 'Handmade fettuccine, garlic cream sauce, shaved parmesan.',
    isVeg: true,
    available: true,
    prepTimeMins: 14,
    station: 'HOT_KITCHEN',
    modifierGroups: [
      {
        id: 'mg-pasta-add',
        name: 'Add Protein',
        required: false,
        options: [
          { id: 'opt-chicken', name: 'Grilled Chicken Breasts', priceDelta: 110 },
          { id: 'opt-shrimp', name: 'Sautéed Garlic Shrimp', priceDelta: 160 },
        ],
      },
    ],
  },
  {
    id: 'mi-401',
    menuNumber: 'BEV-01',
    name: 'Garden Mint & Cucumber Gin Fizz',
    category: 'Beverages',
    price: 280,
    description: 'Botanical gin, muddled cucumber, mint leaves, sparkling tonic.',
    isVeg: true,
    available: true,
    prepTimeMins: 5,
    station: 'BAR',
    modifierGroups: [],
  },
  {
    id: 'mi-402',
    menuNumber: 'BEV-02',
    name: 'Passionfruit Elderflower Mocktail',
    category: 'Beverages',
    price: 220,
    description: 'Fresh passionfruit puree, elderflower syrup, crushed ice, soda.',
    isVeg: true,
    available: true,
    prepTimeMins: 4,
    station: 'BAR',
    modifierGroups: [],
  },
  {
    id: 'mi-403',
    menuNumber: 'BEV-03',
    name: 'Double Espresso Roast',
    category: 'Beverages',
    price: 150,
    description: '100% Arabica artisanal espresso shot.',
    isVeg: true,
    available: true,
    prepTimeMins: 3,
    station: 'BAR',
    modifierGroups: [],
  },
  {
    id: 'mi-501',
    menuNumber: 'DES-01',
    name: 'Signature Artisan Tiramisu',
    category: 'Desserts',
    price: 320,
    description: 'Mascarpone cream, espresso ladyfingers, cocoa dust, gold leaf.',
    isVeg: true,
    available: true,
    prepTimeMins: 6,
    station: 'COLD_PREP',
    modifierGroups: [],
  },
  {
    id: 'mi-502',
    menuNumber: 'DES-02',
    name: 'Molten Belgian Chocolate Lava Cake',
    category: 'Desserts',
    price: 350,
    description: 'Warm chocolate cake with gooey center, vanilla bean ice cream.',
    isVeg: true,
    available: true,
    prepTimeMins: 10,
    station: 'HOT_KITCHEN',
    modifierGroups: [],
  },
  {
    id: 'mi-601',
    menuNumber: 'SPC-01',
    name: 'Chef Special Seafood Paella',
    category: 'Chef Specials',
    price: 890,
    description: 'Saffron rice, tiger prawns, mussels, calamari, chorizo sausage.',
    isVeg: false,
    available: true,
    prepTimeMins: 25,
    station: 'HOT_KITCHEN',
    modifierGroups: [],
  },
];

export const INITIAL_POS_ORDERS = [
  {
    id: 'ord-9001',
    orderNumber: 'ORD-20260813-0001',
    orderType: 'DINE_IN',
    tableId: 'tbl-VIP2',
    tableLabel: 'VIP Lounge 02',
    guestCount: 3,
    status: 'IN_PROGRESS',
    items: [
      {
        id: 'oi-101',
        menuItemId: 'mi-101',
        name: 'Pan-Seared Garlic Butter Scallops',
        quantity: 2,
        unitPrice: 450,
        modifiers: [{ id: 'opt-med', name: 'Medium', priceDelta: 0 }],
        lineTotal: 900,
        kitchenStatus: 'PREPARING',
        fired: true,
        note: 'Serve appetizers first',
      },
      {
        id: 'oi-102',
        menuItemId: 'mi-401',
        name: 'Garden Mint & Cucumber Gin Fizz',
        quantity: 3,
        unitPrice: 280,
        modifiers: [],
        lineTotal: 840,
        kitchenStatus: 'SERVED',
        fired: true,
        note: '',
      },
    ],
    subtotal: 1740,
    taxTotal: 87,
    discountTotal: 0,
    total: 1827,
    currency: 'INR',
    openedBy: 'Server - Priya Sharma',
    createdAt: '2026-08-13T14:15:00.000Z',
  },
];
